# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{v}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Florian A\303\237mann"]
  s.date = %q{2009-12-06}
  s.description = %q{v is for versioned. It's is currently only a threaded wrapper for the git commands or procedures. In the future it should provide a generic interface for diverse VCSs.}
  s.email = %q{florian.assmann@email.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".watchr",
     ".yardoc",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "auto_commit.rb",
     "lib/v.rb",
     "lib/v/adapters.rb",
     "lib/v/adapters/git.rb",
     "lib/v/adapters/git/branches.rb",
     "lib/v/adapters/git/commits.rb",
     "lib/v/adapters/git/environment.rb",
     "lib/v/adapters/git/index.rb",
     "lib/v/adapters/git/object.rb",
     "lib/v/adapters/git/object_types/blob.rb",
     "lib/v/adapters/git/object_types/commit.rb",
     "lib/v/adapters/git/object_types/tag.rb",
     "lib/v/adapters/git/object_types/tree.rb",
     "lib/v/adapters/git/operations/add_to_index.rb",
     "lib/v/adapters/git/operations/branch.rb",
     "lib/v/adapters/git/operations/commit_index.rb",
     "lib/v/adapters/git/operations/diff_index.rb",
     "lib/v/adapters/git/operations/initialize_repository.rb",
     "lib/v/adapters/git/operations/list_files.rb",
     "lib/v/adapters/git/operations/list_tree.rb",
     "lib/v/adapters/git/operations/push_references_to_remote.rb",
     "lib/v/adapters/git/operations/remove_from_index.rb",
     "lib/v/adapters/git/operations/reset_index.rb",
     "lib/v/adapters/git/operations/show_log.rb",
     "lib/v/adapters/git/operations/show_object.rb",
     "lib/v/adapters/git/operations/tag.rb",
     "lib/v/adapters/git/participation.rb",
     "lib/v/adapters/git/remotes.rb",
     "lib/v/adapters/git/status.rb",
     "lib/v/arguments.rb",
     "lib/v/errors.rb",
     "lib/v/future.rb",
     "lib/v/operation.rb",
     "lib/v/worker.rb",
     "test/teststrap.rb",
     "test/v_test.rb",
     "test/work_tree/file",
     "v.gemspec"
  ]
  s.homepage = %q{http://github.com/boof/v}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["fastthread"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{'florian' says: v is talking git.}
  s.test_files = [
    "test/teststrap.rb",
     "test/v_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<fastthread>, [">= 1.0.7"])
    else
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<fastthread>, [">= 1.0.7"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<fastthread>, [">= 1.0.7"])
  end
end

